name: Build Docker Image and Upload as Artifact

on:
  push:
    branches:
      - main

jobs:
  build_and_upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker/setup-buildx-action@v1
        with:
          dockerfile: Dockerfile  # Replace with the path to your Dockerfile

      - name: Build Docker Image
        run: docker build -t insightiq/aswin-nginx:latest .
        # Replace 'my-node-app' with your desired image name/tag

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker Image to Docker Hub
        run: docker push insightiq/aswin-nginx:latest
      
      - name: Upload Docker file as artifact
        uses: actions/upload-artifact@v2
        with:
          name: Dockerfile
          path: Dockerfile
