name: Build Docker Image and Upload as Artifact

on:
  push:
    branches:
      - main

jobs:
  build_and_upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: actions/setup-docker@v2

      - name: Build Docker Image
        run: docker build -t aswin-nginxapp:latest .
       

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker Image to Docker Hub
        run: docker push aswin-nginxapp:latest
       

      - name: Upload Docker Image as Artifact
        uses: actions/upload-artifact@v2
        with:
          name: docker-image
          path: /var/lib/docker
